let commandlineflashcards =

    [
    {"Term": "pwd", "Definition": "print working directory"},
    {"Term": "hostname", "Definition": "my computer's network name"},
    {"Term": "mkdir", "Definition": "make directory"},
    {"Term": "cd", "Definition": "change directory"},
    {"Term": "cd ..", "Definition": "navigates up one directory"},
    {"Term": "ls", "Definition": "list directory"},
    {"Term": "ls -a", "Definition": "lists all contents in the working directory, including hidden files and directories"},
    {"Term": "ls -l", "Definition": "lists all contents of a directory in long format"},
    {"Term": "ls -t", "Definition": "orders files and directories by the time they were last modified"},
    {"Term": "rmdir", "Definition": "remove directory"},
    {"Term": "pushd", "Definition": "push directory"},
    {"Term": "popd", "Definition": "pop directory"},
    {"Term": "cp", "Definition": "copy a file or directory"},
    {"Term": "mv", "Definition": "move a file or directory"},
    {"Term": "less", "Definition": "page through a file"},
    {"Term": "cat", "Definition": "print the whole file"},
    {"Term": "xargs", "Definition": "execute arguments"},
    {"Term": "find", "Definition": "find files"},
    {"Term": "grep", "Definition": "find things inside files", "Example": "$ grep 'Mount' mountains.txt"},
    {"Term": "grep -i", "Definition": "enables the command to be case insensitive"},
    {"Term": "grep -r", "Definition": "searches all files in a directory and outputs filenames and lines containing matched results"},
    {"Term": "grep -rl", "Definition": "searches all files in a directory and outputs only filenames with matched results"},
    {"Term": "man", "Definition": "read a manual page"},
    {"Term": "apropos", "Definition": "find what manual page is appropriate"},
    {"Term": "env", "Definition": "look at your environment"},
    {"Term": "echo", "Definition": "print some arguments"},
    {"Term": "export", "Definition": "export/set a new environment variable"},
    {"Term": "exit", "Definition": "exit the shell"},
    {"Term": "sudo", "Definition": "become super user root"},
    {"Term": ">", "Definition": "takes the standard output of the command on the left, and redirects it to the file on the right", "Example": "$ cat oceans.txt > continents.txt"},
    {"Term": ">>", "Definition": "takes the standard output of the command on the left and appends (adds) it to the file on the right", "Example": "$ cat glaciers.txt >> rivers.txt"},
    {"Term": "<", "Definition": "takes the standard input from the file on the right and inputs it into the program on the left", "Example": "$ cat < lakes.txt"},
    {"Term": "~/.bash_profile", "Definition": "the name of file used to store environment settings"},
    {"Term": "alias", "Definition": "allows you to create keyboard shortcuts, or aliases, for commonly used commands", "Example": "alias pd='pwd'"},
    {"Term": "*", "Definition": "selects all of the files in the current directory"},
    {"Term": "home", "Definition": "an environment variable that displays the path of the home directory"},
    {"Term": "path", "Definition": "an environment variable that stores a list of directories separated by a colon"},
    {"Term": "rm", "Definition": "deletes files"},
    {"Term": "rm -r", "Definition": "deletes a directory and all of its child directories"},
    {"Term": "sort", "Definition": "takes a filename or standard input and orders each line alphabetically, printing it to standard output"},
    {"Term": "source", "Definition": "activates the changes in ~/.bash_profile for the current session"},
    {"Term": "touch", "Definition": "creates a new file inside the working directory"}
    {"Term": "uniq", "Definition": "takes a filename or standard input and prints out every line, removing any exact duplicates"}
    ]
