let cssflashcards =

    [
    {"Term": "CSS", "Definition": "CSS stands for Cascading Style Sheets. CSS describes how HTML elements are to be displayed on screen, paper, or in other media"},
    {"Term": "Selector", "Definition": "points to the HTML element you want to style", "Example": "HTMLselector {textcolor:blue;}"},
    {"Term": "Declaration", "Definition": "includes a CSS property name and a value, separated by a colon. A CSS declaration always ends with a semicolon, and declaration blocks are surrounded by curly braces.", "Example": "h1 {declaration:value;}"},
    {"Term": "id Selector", "Definition": " (#) The id selector uses the id attribute of an HTML element to select a specific element. The id of an element should be unique within a page, so the id selector is used to select one unique element", "Example": "#idgoeshere {color: red;}"},
    {"Term": "class Selector", "Definition": "The class selector selects elements with a specific class attribute. To select elements with a specific class, write a period (.) character, followed by the name of the class.", "Example": ".classname{color:red;}"},
    {"Term": "Comment", "Definition": "(/* */) Comments are used to explain the code, and may help when you edit the source code at a later date. Comments are ignored by browsers"},
    {"Term": "background-color:", "Definition": "set the background color for HTML elements"},
    {"Term": "text-color:", "Definition": "set the text-color for an HTML element"},
    {"Term": "border:", "Definition": "sets properties of border lines for HTML elements"},
    {"Term": "RGB Value", "Definition": "a color can be specified as an RGB value, using this formula: rgb(red, green, blue). Each parameter (red, green, and blue) defines the intensity of the color between 0 and 255."},
    {"Term": "HEX Value", "Definition": "In HTML, a color can be specified using a hexadecimal value in the form: #rrggbb"},
    {"Term": "HSL Value", "Definition": " a color can be specified using hue, saturation, and lightness (HSL) in the form: hsl(hue, saturation, lightness)"},
    {"Term": "background-image:", "Definition": "specifies an image to use as the background of an element. By default, the image is repeated so it covers the entire element", "Example": "body {background-image: url('imagename.gif');}"},
    {"Term": "background-repeat: repeat-x;", "Definition": "used to repeat background image only horizontally"},
    {"Term": "background-repeat: no-repeat;", "Definition": "sets the background image so that it only is displayed once (not repeated)"},
    {"Term": "background-attachment:", "Definition": "Sets whether a background image is fixed or scrolls with the rest of the page"},
    {"Term": "background-origin:", "Definition": "Specifies where the background image(s) is/are positioned"},
    {"Term": "background-position", "Definition": "Sets the starting position of a background image"},
    {"Term": "background-repeat", "Definition": "Sets how a background image will be repeated"},
    {"Term": "background-size", "Definition": "Specifies the size of the background image(s)"},
    {"Term": "border-bottom", "Definition": "Sets all the bottom border properties in one declaration. Each border side has their own declaration (top, bottom, left, right)"},
    {"Term": "border-radius", "Definition": "Sets all the four border-radius properties for rounded corners"},
    {"Term": "border-width", "Definition": "Sets the width of the four borders (can be used on seperate border sides as well)"},
    {"Term": "margin", "Definition": "used to create space around elements, outside of any defined borders"},
    {"Term": "auto margin", "Definition": "You can set the margin property to auto to horizontally center the element within its container"},
    {"Term": "padding", "Definition": "used to generate space around an element's content, inside of any defined borders"},
    {"Term": "height:", "Definition": "sets the height of an element"},
    {"Term": "width", "Definition": "sets the width of an element"},
    {"Term": "max-height and max-width", "Definition": "sets the maximum height or width that an element can be"},
    {"Term": "min-height and min-width", "Definition": "Sets the minimum height or width of an element"},
    {"Term": "CSS Box Model", "Definition": "The CSS box model is essentially a box that wraps around every HTML element. It consists of: margins, borders, padding, and the actual content"},
    {"Term": "Outline", "Definition": "An outline is a line that is drawn around elements, OUTSIDE the borders, to make the element 'stand out'.Style, Color, Width, and Offset properties can be assigned to it. "},
    {"Term": "color", "Definition": "Sets the color of text"},
    {"Term": "direction", "Definition": "Specifies the text direction/writing direction"},
    {"Term": "letter-spacing", "Definition": "Increases or decreases the space between characters in a text"},
    {"Term": "text-align", "Definition": "Specifies the horizontal alignment of text"},
    {"Term": "text-overflow", "Definition": "Specifies how overflowed content that is not displayed should be signaled to the user"},
    {"Term": "vertical-align", "Definition": "Sets the vertical alignment of an element"},
    {"Term": "Font Families", "Definition": "generic family - a g roup of font families with a similar look (like 'Serif' or 'Monospace'). font family - a specific font family (like 'Times New Roman' or 'Arial')"},
    {"Term": "Font", "Definition": "sets font properties. Properties can include: -family, -size, -style, -variant, and -weight"},
    {"Term": "Links", "Definition": "have four states: link, visited, hover and active. Each state can be styled using any CSS property"}
    ]
